'use strict';

const { describe, it } = require('node:test');
const assert = require('node:assert');
const { execSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const HOOKS_DIR = path.join(__dirname, '..', '..', '.githooks');

describe('Git Hooks Tests', () => {

    describe('commit-msg hook', () => {
        const hookPath = path.join(HOOKS_DIR, 'commit-msg');

        function runCommitMsgHook(message) {
            const tmpFile = path.join(__dirname, '_test_commit_msg.tmp');
            fs.writeFileSync(tmpFile, message);
            try {
                execSync(`bash "${hookPath}" "${tmpFile}"`, {
                    encoding: 'utf8',
                    stdio: 'pipe'
                });
                return { passed: true };
            } catch (err) {
                return { passed: false, output: err.stderr || err.stdout };
            } finally {
                fs.unlinkSync(tmpFile);
            }
        }

        // --- Valid messages ---
        it('accepts "feat: description"', () => {
            const result = runCommitMsgHook('feat: add room support');
            assert.strictEqual(result.passed, true);
        });

        it('accepts "fix: description"', () => {
            const result = runCommitMsgHook('fix: resolve null pointer');
            assert.strictEqual(result.passed, true);
        });

        it('accepts "refactor: description"', () => {
            const result = runCommitMsgHook('refactor: extract receiver module');
            assert.strictEqual(result.passed, true);
        });

        it('accepts "test: description"', () => {
            const result = runCommitMsgHook('test: add unit tests for RoomManager');
            assert.strictEqual(result.passed, true);
        });

        it('accepts "docs: description"', () => {
            const result = runCommitMsgHook('docs: update changelog');
            assert.strictEqual(result.passed, true);
        });

        it('accepts "chore: description"', () => {
            const result = runCommitMsgHook('chore: update package.json');
            assert.strictEqual(result.passed, true);
        });

        it('accepts "style: description"', () => {
            const result = runCommitMsgHook('style: fix CSS indentation');
            assert.strictEqual(result.passed, true);
        });

        it('accepts "perf: description"', () => {
            const result = runCommitMsgHook('perf: optimize buffer allocation');
            assert.strictEqual(result.passed, true);
        });

        it('accepts scoped messages like "feat(rooms): description"', () => {
            const result = runCommitMsgHook('feat(rooms): add join support');
            assert.strictEqual(result.passed, true);
        });

        it('accepts breaking change marker "feat!: description"', () => {
            const result = runCommitMsgHook('feat!: redesign message protocol');
            assert.strictEqual(result.passed, true);
        });

        it('accepts scoped breaking change "refactor(api)!: description"', () => {
            const result = runCommitMsgHook('refactor(api)!: change handler interface');
            assert.strictEqual(result.passed, true);
        });

        it('accepts merge commits (auto-generated by git)', () => {
            const result = runCommitMsgHook("Merge branch 'feature/rooms' into main");
            assert.strictEqual(result.passed, true);
        });

        // --- Invalid messages ---
        it('rejects messages without a type prefix', () => {
            const result = runCommitMsgHook('updated some stuff');
            assert.strictEqual(result.passed, false);
        });

        it('rejects messages with invalid type', () => {
            const result = runCommitMsgHook('feature: add rooms');
            assert.strictEqual(result.passed, false);
        });

        it('rejects messages missing colon-space separator', () => {
            const result = runCommitMsgHook('feat add rooms');
            assert.strictEqual(result.passed, false);
        });

        it('rejects empty description after type', () => {
            const result = runCommitMsgHook('feat: ');
            assert.strictEqual(result.passed, false);
        });

        it('rejects first line longer than 350 characters', () => {
            const longMsg = 'feat: ' + 'a'.repeat(400); // 76 chars total
            const result = runCommitMsgHook(longMsg);
            assert.strictEqual(result.passed, false);
        });

        it('accepts first line exactly 350 characters', () => {
            const msg = 'feat: ' + 'a'.repeat(344); // 72 chars total
            const result = runCommitMsgHook(msg);
            assert.strictEqual(result.passed, true);
        });
    });

    describe('Hook files exist and are executable', () => {
        const hooks = ['pre-commit', 'commit-msg', 'pre-push'];

        for (const hook of hooks) {
            it(`${hook} exists`, () => {
                const hookPath = path.join(HOOKS_DIR, hook);
                assert.strictEqual(fs.existsSync(hookPath), true, `${hook} file should exist`);
            });

            it(`${hook} is executable`, () => {
                const hookPath = path.join(HOOKS_DIR, hook);
                try {
                    fs.accessSync(hookPath, fs.constants.X_OK);
                    assert.ok(true);
                } catch {
                    assert.fail(`${hook} should be executable`);
                }
            });

            it(`${hook} starts with a shebang line`, () => {
                const hookPath = path.join(HOOKS_DIR, hook);
                const content = fs.readFileSync(hookPath, 'utf8');
                assert.ok(content.startsWith('#!/bin/bash'), `${hook} should start with #!/bin/bash`);
            });
        }
    });
});
